- name: Add a main user
  user:
    name: "{{ user }}"

- name: Set permission of main user home directory
  file:
    path: "/home/{{ user }}"
    mode: 0755

- name: Create .ssh directory
  file:
    path: "{{ ssh_key_path | dirname }}"
    state: directory
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0700

- name: Copy authorized keys
  copy:
    content: "{{ ssh_pub_key }}"
    dest: "{{ ssh_auth_key_path }}"
    owner: "{{ user }}"
    group: "{{ user }}"
    mode: 0600
