- name: Install libraries
  apt:
    pkg: "{{ item }}"
    state: installed
  with_items:
    - autoconf
    - automake
    - bison
    - gcc
    - git
    - openssl
    - patch
    - tmux
    - curl
    - libjansson-dev
    - libcurl4-openssl-dev
    - cpulimit
